# Generated by Django 3.0.4 on 2020-03-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('number_machine', models.IntegerField()),
                ('year_of_commissioning', models.DateField()),
                ('engine_brand', models.CharField(blank=True, default=None, max_length=50)),
                ('engine_number', models.CharField(blank=True, default=None, max_length=50)),
                ('capacity', models.FloatField(blank=True, default=None)),
                ('costs_at_rate', models.FloatField(blank=True, default=None)),
                ('dizmaslo', models.FloatField(blank=True, default=None)),
                ('turbocharger_mark', models.CharField(blank=True, default=None, max_length=50)),
                ('turbocharger_count', models.SmallIntegerField(blank=True, default=None)),
                ('filtr_air', models.CharField(blank=True, default=None, max_length=6)),
                ('filtr_fuel', models.CharField(blank=True, default=None, max_length=6)),
                ('filtr_dizmaslo', models.CharField(blank=True, default=None, max_length=6)),
                ('filtr_gidravlichni', models.CharField(blank=True, default=None, max_length=6)),
                ('lining_blocks_mark', models.CharField(blank=True, max_length=30)),
                ('lining_blocks_count', models.SmallIntegerField(blank=True)),
                ('lining_pidpiiki_mark', models.CharField(blank=True, max_length=30)),
                ('lining_pidpiiki_count', models.CharField(blank=True, max_length=30)),
                ('compressor_mark', models.CharField(blank=True, max_length=30)),
                ('compressor_count', models.SmallIntegerField(blank=True)),
                ('diametr_wheel_pairs', models.CharField(blank=True, default=None, max_length=30)),
                ('battery_kind', models.CharField(blank=True, max_length=40)),
                ('battery_count', models.CharField(blank=True, max_length=30)),
                ('battery_last_replacement', models.CharField(blank=True, max_length=50)),
                ('battery_count_need', models.CharField(blank=True, max_length=10)),
                ('date_ost_kr', models.DateField(blank=True, null=True)),
                ('initial_value', models.FloatField(blank=True, default=None)),
                ('residual_value', models.FloatField(blank=True, default=None)),
                ('depreciation_end_date', models.DateField()),
                ('dizmaslo_mark', models.CharField(max_length=20)),
                ('dizmaslo_volume', models.IntegerField()),
                ('transmission_fluid_mark', models.CharField(blank=True, max_length=100)),
                ('transmission_fluid_volume', models.IntegerField(blank=True)),
                ('hydraulic_fluid_mark', models.CharField(blank=True, max_length=100)),
                ('hydraulic_fluid_volume', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
