# Generated by Django 3.0.4 on 2020-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='fix_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
