# Generated by Django 3.0.4 on 2020-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_fix_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='fix_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
