# Generated by Django 3.0.4 on 2020-03-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_brigade'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='breakage',
            field=models.BooleanField(default=False),
        ),
    ]
