# Generated by Django 3.0.4 on 2020-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_fix_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
