# Generated by Django 3.0.4 on 2020-03-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_machine_breakage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('url', models.URLField(default=None)),
            ],
        ),
    ]
