# Generated by Django 3.0.4 on 2020-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('4', 'Дуже критичний, потребує терміновий ремонт'), ('3', 'Потребує капітального ремонту'), ('2', 'Не терміново'), ('1', 'Невідомо, потрібен технічний інженер'), ('5', 'невідомо'), ('0', 'В нормальному стані')], default='0', max_length=1),
        ),
    ]
