# Generated by Django 3.0.4 on 2020-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machinename'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinename',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
