# Generated by Django 3.0.4 on 2020-05-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_condition',
            field=models.CharField(choices=[('0', 'В робочому стані'), ('1', 'Не термінова несправність. Поки працює за графіком'), ('2', 'Є несправність. Перевіряється техніком'), ('3', 'Є несправність. Інформацію дізнатись у інженера'), ('4', 'Є несправність'), ('5', 'Знаходиться на ремонті'), ('6', 'На ремонті. Інформація у інженера')], default='0', max_length=1),
        ),
    ]
