# Generated by Django 3.0.4 on 2020-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_machine_machine_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_condition',
            field=models.CharField(choices=[('0', 'В робочому стані'), ('1', 'Не термінова несправність. Поки працює за графіком'), ('3', 'Є несправність. Інформація переправлена техніку та інженеру'), ('2', 'Є несправність. Перевіряється техніком'), ('4', 'Є несправність. Інформацію дізнатись у інженера'), ('5', 'Є несправність'), ('6', 'Знаходиться на ремонті'), ('7', 'На ремонті. Інформація у інженера')], default='0', max_length=1),
        ),
    ]
