# Generated by Django 3.0.4 on 2020-03-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20200316_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinename',
            name='url',
        ),
    ]
