# Generated by Django 3.0.4 on 2020-03-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_remove_machinename_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machines.MachineName'),
            preserve_default=False,
        ),
    ]
