# Generated by Django 3.0.4 on 2020-03-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_machine_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
    ]
