# Generated by Django 3.0.4 on 2020-03-19 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_remove_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='breakage_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='info_about_breakage',
            field=models.TextField(blank=True, default=''),
        ),
    ]
