# Generated by Django 3.0.4 on 2020-03-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_auto_20200319_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='info_about_breakage',
            new_name='breakage_info',
        ),
    ]
