# Generated by Django 3.0.4 on 2020-03-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_auto_20200319_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='capacity',
        ),
        migrations.AddField(
            model_name='machine',
            name='rated_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='breakage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='breakage_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='costs_at_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='depreciation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='diametr_wheel_pairs',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='dizmaslo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='filtr_air',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='filtr_dizmaslo',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='filtr_fuel',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='filtr_gidravlichni',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='initial_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='number_machine',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='machine',
            name='residual_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='year_of_commissioning',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Turbocharger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=30, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbochargers', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionFluid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_fluid', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='LiningPidpiiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.CharField(blank=True, max_length=10, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pidpiikies', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='LiningBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.SmallIntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='HydraulicFluid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydraulic_fluid', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('dizmaslo', models.CharField(blank=True, max_length=50, null=True)),
                ('gidravlichni', models.CharField(blank=True, max_length=50, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Dizmaslo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismaslos', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Compressor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=30, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compressors', to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(blank=True, max_length=40, null=True)),
                ('count', models.CharField(blank=True, max_length=30, null=True)),
                ('last_replacement', models.DateField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batteries', to='machines.Machine')),
            ],
        ),
    ]
