# Generated by Django 3.0.4 on 2020-03-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0012_auto_20200321_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='compressor',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dizmaslo',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='engine',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hydraulicfluid',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liningblock',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='liningpidpiiki',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transmissionfluid',
            name='empty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turbocharger',
            name='empty',
            field=models.BooleanField(default=True),
        ),
    ]
