# Generated by Django 3.0.4 on 2020-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0013_auto_20200321_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
