# Generated by Django 3.0.4 on 2020-03-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0015_auto_20200321_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dizmaslo',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dizmaslos', to='machines.Machine'),
        ),
    ]
