# Generated by Django 3.0.4 on 2020-04-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_auto_20200321_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='works_day',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
