# Generated by Django 3.0.4 on 2020-04-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0017_machine_works_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='works_day',
            new_name='work_days',
        ),
    ]
