# Generated by Django 3.0.4 on 2020-04-16 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0018_auto_20200416_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_used_data',
            field=models.DateField(default=datetime.date(2009, 10, 5)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='work_days',
            field=models.IntegerField(default=0),
        ),
    ]
