# Generated by Django 3.0.4 on 2020-05-06 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machine_name'),
        ('senior_machinist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seniormachinist',
            name='date_start_work',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seniormachinist',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.Machine'),
        ),
    ]
