# Generated by Django 3.0.4 on 2020-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_machinist', '0002_auto_20200506_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniormachinist',
            name='telephone1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='seniormachinist',
            name='telephone2',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
