# Generated by Django 3.0.4 on 2020-05-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senior_machinist', '0003_auto_20200506_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrigadeMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telephone1', models.CharField(blank=True, default='', max_length=30)),
                ('telephone2', models.CharField(blank=True, default='', max_length=30)),
                ('seniormachinist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_machinist.SeniorMachinist')),
            ],
        ),
    ]
