# Generated by Django 3.0.4 on 2020-05-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_machinist', '0005_auto_20200506_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='masloinforeport',
            name='marka',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='masloinforeport',
            name='vidano',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='tempreport',
            name='stage',
            field=models.CharField(choices=[('no', 'Пустий звіт'), ('strt', 'Початок створення'), ('part', 'Частично заповнений'), ('full', 'Заповнений'), ('fwdi', 'Відісланий інженеру'), ('chki', 'Звіт перевірений інженером'), ('fwdd', 'Відісланий директору'), ('chkd', 'Звіт перевірений директором')], default='no', max_length=4),
        ),
    ]
