# Generated by Django 3.0.4 on 2020-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_machinist', '0006_auto_20200506_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempreport',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
