# Generated by Django 3.0.4 on 2020-05-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_machinist', '0007_auto_20200506_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motoandfuelinforeport',
            old_name='fuel_after',
            new_name='km_after',
        ),
        migrations.RenameField(
            model_name='motoandfuelinforeport',
            old_name='fuel_before',
            new_name='km_before',
        ),
        migrations.AddField(
            model_name='tempreport',
            name='km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
