# Generated by Django 3.0.4 on 2020-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senior_machinist', '0008_auto_20200506_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seniormachinist',
            name='avatar',
            field=models.ImageField(blank=True, default='no-image.png', upload_to='employees'),
        ),
    ]
