# Generated by Django 3.0.4 on 2020-04-17 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senior_driver', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True)),
                ('telephone1', models.CharField(blank=True, default='', max_length=15)),
                ('telephone2', models.CharField(blank=True, default='', max_length=15)),
                ('avatar', models.ImageField(blank=True, upload_to='employees')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_completion', models.DateTimeField(auto_now_add=True)),
                ('updated_data', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('checked', models.BooleanField(blank=True, default=False)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.Engineer')),
                ('filled_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_driver.SeniorDriver')),
            ],
        ),
        migrations.CreateModel(
            name='MachineReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motohour', models.FloatField()),
                ('fuel', models.FloatField()),
                ('breakage', models.BooleanField(default=False)),
                ('breakage_info', models.TextField(blank=True, null=True)),
                ('breakage_date_start', models.DateField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.Report')),
            ],
        ),
    ]
