# Generated by Django 3.0.4 on 2020-03-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('senior_driver', '0001_initial'),
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_completion', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('motohour', models.FloatField()),
                ('fuel', models.FloatField()),
                ('breakage', models.BooleanField(default=False)),
                ('filled_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='senior_driver.SeniorDriver')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
            ],
        ),
    ]
