# Generated by Django 3.0.4 on 2020-03-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='checked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
