# Generated by Django 3.0.4 on 2020-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_report_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='telephone1',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='engineer',
            name='telephone2',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
