# Generated by Django 3.0.4 on 2020-04-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_remove_machinereport_some'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinereport',
            name='name_machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
