# Generated by Django 3.0.4 on 2020-04-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0004_machinereport_name_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinereport',
            name='name_machine',
        ),
        migrations.AddField(
            model_name='machinereport',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
