# Generated by Django 3.0.4 on 2020-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0005_report_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='avatar',
        ),
    ]
