# Generated by Django 3.0.4 on 2020-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0006_auto_20200319_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='avatar',
        ),
        migrations.AddField(
            model_name='engineer',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='employees'),
        ),
    ]
