# Generated by Django 3.0.4 on 2020-03-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_auto_20200321_2117'),
        ('engineer', '0007_auto_20200319_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated_data',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_of_completion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='MahineReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motohour', models.FloatField()),
                ('fuel', models.FloatField()),
                ('breakage', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.Report')),
            ],
        ),
    ]
