# Generated by Django 3.0.4 on 2020-03-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0016_auto_20200321_2117'),
        ('engineer', '0008_auto_20200326_1349'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MahineReport',
            new_name='MachineReport',
        ),
    ]
