# Generated by Django 3.0.4 on 2020-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_auto_20200315_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='employees'),
        ),
    ]
