# Generated by Django 3.0.4 on 2020-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senior_driver', '0004_seniordriver_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seniordriver',
            old_name='image',
            new_name='avatar',
        ),
    ]
